name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Core v1.12.0 with asnlookup"
        default: "v1.12.0"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Set up info
        id: info
        run: |
          set -e
          VERSION=$(make -f Makefile.release version)
          COMMIT=$(git rev-parse --verify ${{ github.event.inputs.commit }})
          
          if git tag -l "v${VERSION}" | grep -q "v${VERSION}"; then
            echo "v${VERSION} already exists"
            exit 1
          fi

          echo "commit=${COMMIT}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build release binary
        run: make -f Makefile.release release

      - name: Generate SHA256
        run: (cd release; for asset in *tgz; do sha256sum "$asset" > "$asset.sha256"; done)

      - name: Prepare release notes
        run: sed '/+++/,//d' notes/coredns-${{ steps.info.outputs.version }}.md > release.md

      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.info.outputs.version }}
          name: v${{ steps.info.outputs.version }}
          target_commitish: ${{ steps.info.outputs.commit }}
          body_path: release.md
          files: |
            release/*.tgz
            release/*.tgz.sha256
          draft: true
